// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gfs_server.proto
#ifndef GRPC_gfs_5fserver_2eproto__INCLUDED
#define GRPC_gfs_5fserver_2eproto__INCLUDED

#include "gfs_server.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ChunkServer {

class ChunkService final {
 public:
  static constexpr char const* service_full_name() {
    return "ChunkServer.ChunkService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::ChunkServer::HeartBeat* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChunkServer::HeartBeat>> Asyncget_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChunkServer::HeartBeat>>(Asyncget_heartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChunkServer::HeartBeat>> PrepareAsyncget_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChunkServer::HeartBeat>>(PrepareAsyncget_heartbeatRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response, std::function<void(::grpc::Status)>) = 0;
      virtual void get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ChunkServer::HeartBeat>* Asyncget_heartbeatRaw(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ChunkServer::HeartBeat>* PrepareAsyncget_heartbeatRaw(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::ChunkServer::HeartBeat* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChunkServer::HeartBeat>> Asyncget_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChunkServer::HeartBeat>>(Asyncget_heartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChunkServer::HeartBeat>> PrepareAsyncget_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChunkServer::HeartBeat>>(PrepareAsyncget_heartbeatRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response, std::function<void(::grpc::Status)>) override;
      void get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ChunkServer::HeartBeat>* Asyncget_heartbeatRaw(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ChunkServer::HeartBeat>* PrepareAsyncget_heartbeatRaw(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_get_heartbeat_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status get_heartbeat(::grpc::ServerContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_get_heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_heartbeat() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_get_heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_heartbeat(::grpc::ServerContext* /*context*/, const ::ChunkServer::VoidMessage* /*request*/, ::ChunkServer::HeartBeat* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_heartbeat(::grpc::ServerContext* context, ::ChunkServer::VoidMessage* request, ::grpc::ServerAsyncResponseWriter< ::ChunkServer::HeartBeat>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_get_heartbeat<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_get_heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_get_heartbeat() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ChunkServer::VoidMessage, ::ChunkServer::HeartBeat>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response) { return this->get_heartbeat(context, request, response); }));}
    void SetMessageAllocatorFor_get_heartbeat(
        ::grpc::MessageAllocator< ::ChunkServer::VoidMessage, ::ChunkServer::HeartBeat>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ChunkServer::VoidMessage, ::ChunkServer::HeartBeat>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_get_heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_heartbeat(::grpc::ServerContext* /*context*/, const ::ChunkServer::VoidMessage* /*request*/, ::ChunkServer::HeartBeat* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::ChunkServer::VoidMessage* /*request*/, ::ChunkServer::HeartBeat* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_get_heartbeat<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_get_heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_heartbeat() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_get_heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_heartbeat(::grpc::ServerContext* /*context*/, const ::ChunkServer::VoidMessage* /*request*/, ::ChunkServer::HeartBeat* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_heartbeat() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_get_heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_heartbeat(::grpc::ServerContext* /*context*/, const ::ChunkServer::VoidMessage* /*request*/, ::ChunkServer::HeartBeat* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_heartbeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_get_heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_get_heartbeat() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_heartbeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_get_heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_heartbeat(::grpc::ServerContext* /*context*/, const ::ChunkServer::VoidMessage* /*request*/, ::ChunkServer::HeartBeat* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_heartbeat() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ChunkServer::VoidMessage, ::ChunkServer::HeartBeat>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ChunkServer::VoidMessage, ::ChunkServer::HeartBeat>* streamer) {
                       return this->Streamedget_heartbeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_heartbeat(::grpc::ServerContext* /*context*/, const ::ChunkServer::VoidMessage* /*request*/, ::ChunkServer::HeartBeat* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_heartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ChunkServer::VoidMessage,::ChunkServer::HeartBeat>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_get_heartbeat<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_get_heartbeat<Service > StreamedService;
};

}  // namespace ChunkServer


#endif  // GRPC_gfs_5fserver_2eproto__INCLUDED
