// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gfs_server.proto

#include "gfs_server.pb.h"
#include "gfs_server.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ChunkServer {

static const char* ChunkService_method_names[] = {
  "/ChunkServer.ChunkService/get_heartbeat",
};

std::unique_ptr< ChunkService::Stub> ChunkService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChunkService::Stub> stub(new ChunkService::Stub(channel, options));
  return stub;
}

ChunkService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_get_heartbeat_(ChunkService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChunkService::Stub::get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::ChunkServer::HeartBeat* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ChunkServer::VoidMessage, ::ChunkServer::HeartBeat, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_heartbeat_, context, request, response);
}

void ChunkService::Stub::async::get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ChunkServer::VoidMessage, ::ChunkServer::HeartBeat, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_heartbeat_, context, request, response, std::move(f));
}

void ChunkService::Stub::async::get_heartbeat(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_heartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ChunkServer::HeartBeat>* ChunkService::Stub::PrepareAsyncget_heartbeatRaw(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ChunkServer::HeartBeat, ::ChunkServer::VoidMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_heartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ChunkServer::HeartBeat>* ChunkService::Stub::Asyncget_heartbeatRaw(::grpc::ClientContext* context, const ::ChunkServer::VoidMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_heartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChunkService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChunkService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChunkService::Service, ::ChunkServer::VoidMessage, ::ChunkServer::HeartBeat, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChunkService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ChunkServer::VoidMessage* req,
             ::ChunkServer::HeartBeat* resp) {
               return service->get_heartbeat(ctx, req, resp);
             }, this)));
}

ChunkService::Service::~Service() {
}

::grpc::Status ChunkService::Service::get_heartbeat(::grpc::ServerContext* context, const ::ChunkServer::VoidMessage* request, ::ChunkServer::HeartBeat* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ChunkServer

